#2092 fixes room list update loop with locked muc domains
conversejs/converse.js pull request #2268
Opened 2020-10-06 16:54 UTC by vdwijngaert

The `updateRoomList` function gets called after each render, and the `onRoomsFound` handler calls `this.render()`. Looks like the problem is fixed when the `updateRoomList` only gets called on the `shown.bs.model` event. This is needed because the list will not update after re-opening the modal (it does not get destroyed on close).

Linked issue: #2092

2020-10-06 18:02 UTC, jcbrand requested changes
Thanks for the PR @vdwijngaert :)

I've left two review comments.

2020-10-07 06:13 UTC, vdwijngaert commented on src/modals/muc-list.js
>                  () => this.el.querySelector('input[name="server"]').focus(),
It appears moving both listeners to the `initialize` function is a cleaner solution.. What do you think?

2020-10-07 06:13 UTC, vdwijngaert commented on CHANGES.md
> +
Fixed!

2020-10-07 06:16 UTC, vdwijngaert commented on src/modals/muc-list.js
>                  () => this.el.querySelector('input[name="server"]').focus(),
Just double checked, the other listener still works as expected when `locked_muc_domain` is false.

2020-10-07 08:36 UTC, jcbrand commented on src/modals/muc-list.js
>                  () => this.el.querySelector('input[name="server"]').focus(),
Great, thanks!

2020-10-07 08:37 UTC, merged